application: internetactiva
version: 2-1
runtime: python
api_version: 1


handlers:
- url: .*
  script: main.py
- url: /static
  static_dir: static

admin_console:
  pages:
  - name: Agregar contenido
    url: /posts/new
  - name: Editar contenido
    url: /posts/edit
  - name: Salvar (edicion) contenido
    url: /posts/save
  - name: Borrar contenido
    url: /posts/delete
  - name: Borra (del) contenido
    url: /posts/del

